### PR TITLE
(GH-125) Fix dsc provider canonicalization for absent resources

### LINKED ISSUE #125: DSC Base Provider: Canonicalize absent resources properly
When canonicalizing a DSC Resource:

- [x] If the manifest specification is `Absent`, canonicalization should default to the manifest specification without calling `Invoke-DscResource`
- [x] If the manifest specification is `Present`, canonicalization should call `Invoke-DscResource`
  - [x] If the Resource is `Absent`, canonicalization should default to the manifest specification
  - [x] If the Resource is `Present`, canonicalization should compare attributes between the actual and specified and behave as normal (case insensitive but preserving)

Evidence of this canonicalization failure can be [seen in these user logs](https://gist.github.com/104ru/3c274007010ae9b48a5dbd1f23e474ec#file-gistfile1-txt-L2324-L2326).

### PR DESCRIPTION
**Pull request by michaeltlombardi**
Prior to this PR the `canonicalize` method in the DSC Base Provider did some unneccessary work:

- it _always_ called `invoke_get_method` if a resource was not already in the canonicalized cache
- it erroneously canonicalized a resource which **should** exist to values which were returned as `nil` from `invoke_get_method` because DSC returns the ensure value as `absent` and `nil` for other properties

This commit adds logic shortcuts to obviate unneccessary canonicalization of the resource when the should value for `dsc_ensure` is `absent` (because a resource being deleted does not care about casing) as well as when the should value for `dsc_ensure` is `present` but the resource itself does not actually exist on the system (a resource which is being created should treat it's own definition as canonical).

- Resolves #125

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
While this is currently functional, there is some refactoring necessary to make the tests more maintainable and readable; I ran out of time today but will get that in tomorrow.

File: spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb [hunk 1]
```diff
@@ -78,14 +79,129 @@
...
+    let(:base_resource) { resource_name_hash.dup }
+
+    before(:each) do
+      allow(context).to receive(:debug)
+      allow(provider).to receive(:namevar_attributes).and_return(namevar_keys)
+      allow(provider).to receive(:fetch_cached_hashes).and_return(cached_canonicalized_resource)
+      described_class.class_variable_set(:@@cached_canonicalized_resource, []) # rubocop:disable Style/ClassVars
+    end
+
+    after(:all) do
```
Comment (DavidS) [inline spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb:97]: Shouldn't this be 

```suggestion
    after(:each) do
```

or are the test-cases so closely entangled that they need to spill over state?

Comment (michaeltlombardi) [reply spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb:97]: I can def swap this to be each, I think my original logic was we are resetting it in the `before(:each)` and only need to clear it again after they're all done.

Comment (DavidS) [reply spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb:97]: huh - I feel that's even more confusing; if there's something in at the start of the test it seems like that's already a spill-over from a different test? maybe elevate the `after(:each)` to the top-level and remove the duplicate initialisers?

Comment (michaeltlombardi) [reply spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb:97]: We could definitely move the before/after cleanup for the caching to the top scope before(:each) I think.

Comment (michaeltlombardi) [reply spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb]: Done!

**Review by DavidS — APPROVED** [review]
