### PR TITLE
(GH-55) Handle intentionally empty arrays

### LINKED ISSUE #55: Empty Arrays cause casting errors for CIM instances
## Describe the Bug
When passing arguments to `Invoke-DscResource`, a property of an empty array cannot be properly cast to a strongly typed array (e.g. if it expects `[string[]]`, `@()` will not be properly cast). This will cause the invocation to fail.

## Expected Behavior
Empty arrays are sent with their full type information in the property hash.

## Steps to Reproduce
Attempt to apply the following manifest:

```puppet
dsc_userrightsassignment{'Deny RDS Access':
  dsc_identity => [],
  dsc_policy   => 'Deny_log_on_through_Remote_Desktop_Services',
}
```

## Environment
 - ruby-pwsh `0.5.1`
- [dsc-securitypolicydsc](https://forge.puppet.com/modules/dsc/securitypolicydsc)

### PR DESCRIPTION
**Pull request by michaeltlombardi**
Prior to this commit the DSC base provider would occasionally need to send an empty array as a defined property to `Invoke-DscResource`. However, the CIM instance on the other end may not be able to appropriately cast from an empty array to, say a `[String[]]` type; this would cause the run to fail. Furthermore, the provider did not have a way to distinguish between an *absent* setting and an *empty* one. Ruby does not treat empty arrays and nil as the same, even though PowerShell can/does.

This commit adds a special handler for munging the data returned from a get invocation, ensuring that if a property's value is nil AND the property was used for the query AND the resource expects an array, THEN it will set the result to the manifest value or an empty array.

It also strongly types any empty arrays being sent
to `Invoke-DscResource`, as this prevents the casting problem by making the array type casting  explicit instead of merely implicit.

- Resolves #55

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
Lots of rubocop changes since last PR, will address those in an additional maint commit.

File: lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb [hunk 1]
```diff
@@ -283,9 +285,9 @@ def should_to_resource(should, context, dsc_invoke_method)
     # During a Puppet agent run, the code lives in the cache so we can use the file expansion to discover the correct folder.
     root_module_path = $LOAD_PATH.select { |path| path.match?(%r{#{resource[:dscmeta_module_name].downcase}/lib}) }.first
     resource[:vendored_modules_path] = if root_module_path.nil?
-                                         File.expand_path(Pathname.new(__FILE__).dirname + '../../../' + 'puppet_x/dsc_resources')
+                                         File.expand_path(Pathname.new(__FILE__).dirname + '../../../' + 'puppet_x/dsc_resources') # rubocop:disable Style/StringConcatenation
```
Comment (RandomNoun7) [inline lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb:288]: Rubocop: Hey man! You can't do that
Lombardi: STFU
Me: LGTM

Comment (michaeltlombardi) [reply lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb:288]: I felt like in this case, with going up-level, it was more readable/understandable with the + instead of interpolation - looks like steps to get to what you want, imo

Comment (RandomNoun7) [reply lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb:288]: Hey man, you had me at `rubocop:disable`.

File: lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb [hunk 2]
```diff
@@ -560,6 +560,13 @@ def invoke_params(resource)
                                 end
     end
     params_block = interpolate_variables("$InvokeParams = #{format(params)}")
+    # HACK: Handle intentionally empty arrays - need to strongly type them because
+    # CIM instances do not do a consistent job of casting an empty array properly.
+    empty_array_parameters = resource[:parameters].select { |_k, v| v[:value].empty? }
+    empty_array_parameters.each do |name, properties|
+      param_block_name = name.to_s.gsub(/^dsc_/, '')
+      params_block = params_block.gsub("#{param_block_name} = @()", "#{param_block_name} = [#{properties[:mof_type]}]@()")
```
Comment (RandomNoun7) [inline lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb:568]: JFC. I'm both glad you were able to figure this out, and saddened that you had to. I like it though.

Comment (michaeltlombardi) [reply lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb:568]: It's an extremely unclever hack but it _did_ work in this case.

**Review by RandomNoun7 — APPROVED** [review]
