### PR TITLE
Ensure ruby versions older than 2.3 function correctly

### LINKED ISSUE #28: Broken for Puppet <6 due to use of Ruby 2.0+ features
## Describe the Bug
Releases of this module state support for Puppet <6, while using Ruby features that were introduced in more modern Ruby versions than the one packaged in the Puppet 4 and 5 servers. (1.9)

## Expected Behavior
Catalogs should compile

## Steps to Reproduce
- Install this module
- Try to compile a catalog containing any use of powershell
```puppet
exec { 'echo hello world':
  provider => powershell,
}
```

## Environment
 - Version:
   - Module 0.4.0
   - Puppet 5.3.10
 - Platform CentOS 7.7.1908

### PR DESCRIPTION
**Pull request by binford2k**
Fixes #28

### CODE REVIEW

File: lib/pwsh.rb [hunk 1]
```diff
@@ -54,7 +54,7 @@ def self.instance(cmd, args, options = {})
       if manager.nil? || !manager.alive?
         # ignore any errors trying to tear down this unusable instance
         begin
-          manager&.exit
+          manager.exit if manager
```
Comment (michaeltlombardi) [inline lib/pwsh.rb]: I think to properly guard this it would have to be

```suggestion
          manager.exit if defined?(manager)
```

File: lib/pwsh.rb [hunk 2]
```diff
@@ -54,7 +54,7 @@ def self.instance(cmd, args, options = {})
       if manager.nil? || !manager.alive?
         # ignore any errors trying to tear down this unusable instance
         begin
-          manager&.exit
+          manager.exit if defined?(manager)
```
Comment (glennsarti) [inline lib/pwsh.rb]: This should really be `manager.exit unless manager.nil?`

`defined?(manager)` will still be true it `manager = nil`
